<?php include 'header.phtml'; ?>
<div class="container">

    <div class="row mt-2">
        <div class="col-12">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                    <a href="/" class="btn btn-primary" href=""><i class="fa-sharp fa-solid fa-home"></i></a>
                    <a href="/user/new" class="btn btn-primary" href=""><i class="fa-sharp fa-solid fa-plus"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-12">
            <table class="table">
                <tr>
                    <th>Имя пользователя</th>
                    <th>Отдел</th>
                    <th>email</th>
                    <th>Адрес</th>
                    <th>Телефон</th>
                    <th>Комментарий</th>
                    <th>Управление</th>
                </tr>
                <?php foreach ($users as $user): ?>
                    <tr>
                        <th><?php echo $user['username']; ?></th>
                        <th><?php echo $user['deptname']; ?></th>
                        <th><?php echo $user['email']; ?></th>
                        <th><?php echo $user['address']; ?></th>
                        <th><?php echo $user['phone']; ?></th>
                        <th><?php echo $user['comment']; ?></th>
                        <th>
                            <a href="/users/<?php echo $user['id']; ?>" class="btn btn-primary" href=""><i class="fa-solid fa-pen-to-square"></i></i></a>
                            <a href="/user/delete/<?php echo $user['id']; ?>" class="btn btn-primary" href=""><i class="fa-sharp fa-solid fa-trash"></i></i></a>                
                        </th>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
<?php
include 'footer.phtml';
